spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://your ip/base_platform?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    mode: HTML5
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml